# Generated by Django 5.0.1 on 2025-09-16 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(help_text='Fecha de compra del dispositivo GPS')),
                ('imei', models.CharField(help_text='Número IMEI único del dispositivo', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'IMEI debe tener 15 dígitos')])),
                ('marca', models.CharField(help_text='Marca del dispositivo GPS', max_length=20)),
                ('modelo', models.CharField(help_text='Modelo del dispositivo GPS', max_length=20)),
                ('numero_factura', models.CharField(help_text='Número de factura de compra', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_mantenimiento', 'En Mantenimiento'), ('dañado', 'Dañado'), ('perdido', 'Perdido'), ('dado_de_baja', 'Dado de Baja')], default='disponible', help_text='Estado actual del dispositivo', max_length=20)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra del dispositivo', max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(help_text='Proveedor que vendió el dispositivo', on_delete=django.db.models.deletion.PROTECT, to='entities.proveedor')),
            ],
            options={
                'verbose_name': 'GPS',
                'verbose_name_plural': 'Dispositivos GPS',
                'db_table': 'inventory_gps',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(help_text='Fecha de compra del producto')),
                ('numero_factura', models.CharField(help_text='Número de factura de compra', max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos comprados')),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto')),
                ('categoria', models.CharField(blank=True, help_text='Categoría del producto (cables, herramientas, etc.)', max_length=100)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario del producto', max_digits=10, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, help_text='Precio total de la compra', max_digits=10, null=True)),
                ('stock_actual', models.IntegerField(default=0, help_text='Stock actual disponible')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Stock mínimo requerido')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(help_text='Proveedor que vendió el producto', on_delete=django.db.models.deletion.PROTECT, to='entities.proveedor')),
            ],
            options={
                'verbose_name': 'Otro Producto',
                'verbose_name_plural': 'Otros Productos',
                'db_table': 'inventory_otros',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='SIMCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(help_text='Fecha de compra de la tarjeta SIM')),
                ('numero_factura', models.CharField(help_text='Número de factura de compra', max_length=20)),
                ('numero_chip', models.CharField(help_text='Número de teléfono de la SIM', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Número de chip debe tener 9 dígitos')])),
                ('icc', models.CharField(help_text='Código ICC único de la tarjeta SIM', max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_mantenimiento', 'En Mantenimiento'), ('dañado', 'Dañado'), ('perdido', 'Perdido'), ('dado_de_baja', 'Dado de Baja')], default='disponible', help_text='Estado actual de la tarjeta SIM', max_length=20)),
                ('operadora', models.CharField(blank=True, help_text='Operadora de la tarjeta SIM (Claro, Movistar, etc.)', max_length=50)),
                ('plan', models.CharField(blank=True, help_text='Plan contratado para la SIM', max_length=100)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra de la SIM', max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la SIM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(help_text='Proveedor que vendió la tarjeta SIM', on_delete=django.db.models.deletion.PROTECT, to='entities.proveedor')),
            ],
            options={
                'verbose_name': 'Tarjeta SIM',
                'verbose_name_plural': 'Tarjetas SIM',
                'db_table': 'inventory_simcard',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
