# Generated by Django 5.0.1 on 2025-09-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_cliente_entities_cl_ruc_ccb567_idx_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('activo', 'Activo'), ('asignado', 'Asignado'), ('suspendido', 'Suspendido'), ('en_mantenimiento', 'En Mantenimiento'), ('dañado', 'Dañado'), ('perdido', 'Perdido'), ('dado_de_baja', 'Dado de Baja')], default='disponible', help_text='Estado actual del dispositivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('activo', 'Activo'), ('asignado', 'Asignado'), ('suspendido', 'Suspendido'), ('en_mantenimiento', 'En Mantenimiento'), ('dañado', 'Dañado'), ('perdido', 'Perdido'), ('dado_de_baja', 'Dado de Baja')], default='disponible', help_text='Estado actual de la tarjeta SIM', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['imei'], name='inventory_g_imei_7e5f78_idx'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['estado'], name='inventory_g_estado_ff7db6_idx'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['fecha_compra'], name='inventory_g_fecha_c_34216b_idx'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['marca', 'modelo'], name='inventory_g_marca_7a22a1_idx'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['proveedor', 'estado'], name='inventory_g_proveed_7f68d6_idx'),
        ),
        migrations.AddIndex(
            model_name='otros',
            index=models.Index(fields=['categoria'], name='inventory_o_categor_91ea83_idx'),
        ),
        migrations.AddIndex(
            model_name='otros',
            index=models.Index(fields=['fecha_compra'], name='inventory_o_fecha_c_2c053c_idx'),
        ),
        migrations.AddIndex(
            model_name='otros',
            index=models.Index(fields=['stock_actual'], name='inventory_o_stock_a_0fb54c_idx'),
        ),
        migrations.AddIndex(
            model_name='otros',
            index=models.Index(fields=['proveedor'], name='inventory_o_proveed_0dde04_idx'),
        ),
        migrations.AddIndex(
            model_name='otros',
            index=models.Index(fields=['categoria', 'stock_actual'], name='inventory_o_categor_e62e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['numero_chip'], name='inventory_s_numero__20d55b_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['icc'], name='inventory_s_icc_d2c127_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['estado'], name='inventory_s_estado_0522e3_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['fecha_compra'], name='inventory_s_fecha_c_881c11_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['operadora'], name='inventory_s_operado_0429af_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['proveedor', 'estado'], name='inventory_s_proveed_a8abab_idx'),
        ),
    ]
