# Generated by Django 5.0.1 on 2025-09-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_cliente_entities_cl_ruc_ccb567_idx_and_more'),
        ('inventory', '0002_alter_gps_estado_alter_simcard_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente al que está asignado el dispositivo GPS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_asignados', to='entities.cliente'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['cliente'], name='inventory_g_cliente_c4479d_idx'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['cliente', 'estado'], name='inventory_g_cliente_fdf32b_idx'),
        ),
    ]
