# Generated by Django 5.0.1 on 2025-09-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_cliente_to_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='proceso',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('dañado', 'Dañado'), ('en_reparacion', 'En Reparación'), ('en_mantenimiento', 'En Mantenimiento'), ('dado_de_baja', 'Dado de Baja'), ('en_transito', 'En Tránsito')], default='disponible', help_text='Proceso o condición operativa del GPS', max_length=20),
        ),
        migrations.AlterField(
            model_name='gps',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('no_asignado', 'No Asignado')], default='no_asignado', help_text='Estado de asignación del GPS (asignado/no_asignado)', max_length=20),
        ),
    ]
