# Generated by Django 5.0.1 on 2025-09-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_cliente_entities_cl_ruc_ccb567_idx_and_more'),
        ('inventory', '0005_migrate_estado_to_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='gps',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el dispositivo GPS está activo en el sistema'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_asignado', 'No Asignado'), ('activo', 'Activo'), ('asignado', 'Asignado'), ('suspendido', 'Suspendido'), ('en_mantenimiento', 'En Mantenimiento'), ('dañado', 'Dañado'), ('perdido', 'Perdido'), ('dado_de_baja', 'Dado de Baja')], default='disponible', help_text='Estado actual de la tarjeta SIM', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['is_active'], name='inventory_g_is_acti_1f1247_idx'),
        ),
        migrations.AddIndex(
            model_name='gps',
            index=models.Index(fields=['is_active', 'estado'], name='inventory_g_is_acti_8dc360_idx'),
        ),
    ]
