# Generated by Django 5.0.1 on 2025-09-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_cliente_entities_cl_ruc_ccb567_idx_and_more'),
        ('inventory', '0008_update_existing_proceso_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='simcard',
            name='inventory_s_operado_0429af_idx',
        ),
        migrations.RemoveField(
            model_name='simcard',
            name='operadora',
        ),
        migrations.AddField(
            model_name='simcard',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente al que está asignada la tarjeta SIM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simcards_asignadas', to='entities.cliente'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la tarjeta SIM está activa en el sistema'),
        ),
        migrations.AddField(
            model_name='simcard',
            name='proceso',
            field=models.CharField(choices=[('en_produccion', 'En Producción'), ('dañado', 'Dañado'), ('garantia', 'Garantía'), ('en_mantenimiento', 'En Mantenimiento'), ('dado_de_baja', 'Dado de Baja'), ('en_transito', 'En Tránsito')], default='en_produccion', help_text='Proceso o condición operativa de la SIM', max_length=20),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='estado',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('no_asignado', 'No Asignado')], default='no_asignado', help_text='Estado de asignación de la SIM (asignado/no_asignado)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['cliente'], name='inventory_s_cliente_1077de_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['cliente', 'estado'], name='inventory_s_cliente_d19a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['is_active'], name='inventory_s_is_acti_97bed4_idx'),
        ),
        migrations.AddIndex(
            model_name='simcard',
            index=models.Index(fields=['is_active', 'estado'], name='inventory_s_is_acti_e9064b_idx'),
        ),
    ]
