# Generated by Django 5.0.1 on 2025-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_update_simcard_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='proceso',
            field=models.CharField(choices=[('en_produccion', 'En Producción'), ('dado_de_baja', 'Dado de Baja'), ('en_almacen', 'En Almacén')], default='en_produccion', help_text='Proceso o condición operativa del GPS', max_length=20),
        ),
    ]
