# Generated by Django 5.0.1 on 2025-09-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_update_simcard_proceso_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='proceso',
            field=models.CharField(choices=[('en_produccion', 'En Producción'), ('dañado', 'Dañado'), ('garantia', 'Garantía'), ('en_mantenimiento', 'En Mantenimiento'), ('dado_de_baja', 'Dado de Baja'), ('en_transito', 'En Tránsito')], default='en_produccion', help_text='Proceso o condición operativa del GPS', max_length=20),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='proceso',
            field=models.CharField(choices=[('en_produccion', 'En Producción'), ('dado_de_baja', 'Dado de Baja'), ('en_almacen', 'En Almacén')], default='en_produccion', help_text='Proceso o condición operativa de la SIM', max_length=20),
        ),
    ]
