# Generated by Django 5.0.1 on 2025-09-16 16:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock Bajo'), ('high_sales', 'Ventas Altas'), ('system_error', 'Error del Sistema'), ('performance', 'Rendimiento'), ('security', 'Seguridad')], max_length=20, verbose_name='Tipo de alerta')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='active', max_length=15, verbose_name='Estado')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor umbral')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor actual')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reconocimiento')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconocido por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity'], name='dashboard_a_alert_t_a33178_idx'), models.Index(fields=['status'], name='dashboard_a_status_fcc637_idx'), models.Index(fields=['created_at'], name='dashboard_a_created_fe9d01_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la métrica')),
                ('metric_type', models.CharField(choices=[('sales', 'Ventas'), ('inventory', 'Inventario'), ('users', 'Usuarios'), ('performance', 'Rendimiento'), ('financial', 'Financiero')], max_length=20, verbose_name='Tipo de métrica')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('period_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Tipo de período')),
                ('period_start', models.DateTimeField(verbose_name='Inicio del período')),
                ('period_end', models.DateTimeField(verbose_name='Fin del período')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_metrics', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metric_type', 'period_type'], name='dashboard_m_metric__f8ccf2_idx'), models.Index(fields=['period_start', 'period_end'], name='dashboard_m_period__8d890a_idx'), models.Index(fields=['created_at'], name='dashboard_m_created_6e8eec_idx')],
                'unique_together': {('name', 'period_start', 'period_end')},
            },
        ),
    ]
