# Generated by Django 5.0.1 on 2025-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nombre',
            field=models.CharField(choices=[('ADMIN', 'Administrador del Sistema'), ('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('tecnico', 'Técnico')], help_text='Nombre del rol del usuario', max_length=20, unique=True),
        ),
    ]
