# Generated by Django 5.0.1 on 2025-09-16 05:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_cliente_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Mes correspondiente a la venta')),
                ('fecha_pago', models.TimeField(help_text='Hora del pago realizado')),
                ('numero_operacion', models.CharField(help_text='Número de operación bancaria o comprobante', max_length=10)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('deposito', 'Depósito Bancario'), ('cheque', 'Cheque'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('yape', 'Yape'), ('plin', 'Plin'), ('otro', 'Otro')], help_text='Método de pago utilizado', max_length=20)),
                ('banco', models.TextField(help_text='Banco donde se realizó la operación')),
                ('numero_factura', models.CharField(help_text='Número único de factura', max_length=10, unique=True)),
                ('fecha_generacion_factura', models.DateTimeField(help_text='Fecha y hora de generación de la factura')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la venta')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio total con IGV incluido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe sin IGV (precio/1.18)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('igv', models.DecimalField(decimal_places=2, help_text='Monto del IGV (importe*0.18)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final (importe + igv)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('anulado', 'Anulado')], default='pendiente', help_text='Estado actual de la venta', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza la compra', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='entities.cliente')),
                ('unidad', models.ForeignKey(help_text='Unidad vehicular asociada a la venta', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='entities.unidad')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sales_ventas',
                'ordering': ['-fecha_generacion_factura'],
            },
        ),
    ]
