# Generated by Django 5.0.1 on 2025-09-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_cliente_entities_cl_ruc_ccb567_idx_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['numero_factura'], name='sales_venta_numero__c2f48d_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['estado'], name='sales_venta_estado_784902_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['fecha_generacion_factura'], name='sales_venta_fecha_g_b37702_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['cliente'], name='sales_venta_cliente_ab9beb_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['tipo_pago'], name='sales_venta_tipo_pa_668e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['cliente', 'estado'], name='sales_venta_cliente_8c25c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['mes'], name='sales_venta_mes_7a582a_idx'),
        ),
    ]
