# Generated by Django 5.0.1 on 2025-09-16 05:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_cliente_alter_proveedor_options_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('otro', 'Otro')], help_text='Tipo de trabajo a realizar', max_length=30, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada del tipo de trabajo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Trabajo',
                'verbose_name_plural': 'Tipos de Trabajo',
                'db_table': 'services_tipo_trabajo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Fecha y hora del servicio')),
                ('descripcion', models.TextField(help_text='Descripción detallada del trabajo realizado')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del servicio en soles', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado_servicio', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('reprogramado', 'Reprogramado')], default='pendiente', help_text='Estado actual del servicio', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del servicio')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente que solicita el servicio', on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='entities.cliente')),
                ('gps', models.ForeignKey(blank=True, help_text='Dispositivo GPS utilizado en el servicio (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='inventory.gps')),
                ('sim_card', models.ForeignKey(blank=True, help_text='Tarjeta SIM utilizada en el servicio (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='inventory.simcard')),
                ('tecnico', models.ForeignKey(help_text='Técnico asignado al servicio', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(help_text='Unidad vehicular donde se realiza el servicio', on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='entities.unidad')),
                ('tipo_trabajo', models.ForeignKey(help_text='Tipo de trabajo a realizar', on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='services.tipotrabajo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'services_servicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
