# Generated by Django 5.0.1 on 2025-09-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_tipotrabajo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotrabajo',
            name='nombre',
            field=models.CharField(choices=[('instalacion_nueva', 'Instalación Nueva'), ('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('mantenimiento_correctivo', 'Mantenimiento Correctivo'), ('otro', 'Otro')], help_text='Tipo de trabajo a realizar', max_length=30, unique=True),
        ),
    ]
