# Generated by Django 5.0.1 on 2025-09-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_cliente_entities_cl_ruc_ccb567_idx_and_more'),
        ('services', '0003_alter_tipotrabajo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad vehicular donde se realiza el servicio (opcional para servicios como instalación de cámaras)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='entities.unidad'),
        ),
    ]
