# Generated by Django 5.0.1 on 2025-09-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_make_unidad_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado_servicio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('reprogramado', 'Reprogramado')], default='pendiente', help_text='Estado actual del servicio', max_length=20),
        ),
    ]
