# Generated by Django 5.0.1 on 2025-09-16 05:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o razón social del cliente', max_length=200)),
                ('ruc', models.CharField(help_text='RUC del cliente (11 dígitos)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'RUC debe tener 11 dígitos')])),
                ('direccion', models.TextField(help_text='Dirección completa del cliente')),
                ('contacto', models.CharField(help_text='Nombre de la persona de contacto', max_length=100)),
                ('celular', models.CharField(help_text='Número de celular (9 dígitos)', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Celular debe tener 9 dígitos')])),
                ('correo', models.EmailField(help_text='Correo electrónico del cliente', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'entities_cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto_principal',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(default='000000000', help_text='Número de celular (9 dígitos)', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Celular debe tener 9 dígitos')]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(default='Sin contacto', help_text='Nombre de la persona de contacto', max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='Sin nombre', help_text='Nombre o razón social del proveedor', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(default='Sin dirección', help_text='Dirección completa del proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(help_text='RUC del proveedor (11 dígitos)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'RUC debe tener 11 dígitos')]),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bus', 'Bus'), ('camion', 'Camión'), ('otro', 'Otro')], help_text='Tipo de vehículo', max_length=10)),
                ('placa', models.CharField(help_text='Placa del vehículo (formato peruano)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{6,10}$', 'Formato de placa inválido')])),
                ('marca', models.CharField(help_text='Marca del vehículo', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo del vehículo', max_length=50)),
                ('serie', models.CharField(help_text='Número de serie del vehículo (VIN)', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='entities.cliente')),
            ],
            options={
                'verbose_name': 'Unidad Vehicular',
                'verbose_name_plural': 'Unidades Vehiculares',
                'db_table': 'entities_unidad',
                'ordering': ['placa'],
            },
        ),
    ]
