# Generated by Django 5.0.1 on 2025-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_cliente_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(default='sin@correo.com', help_text='Correo electrónico del proveedor', max_length=254),
        ),
    ]
