# Generated by Django 5.0.1 on 2025-09-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_proveedor_correo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ruc'], name='entities_cl_ruc_ccb567_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='entities_cl_nombre_ae72e0_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['correo'], name='entities_cl_correo_7ace15_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['created_at'], name='entities_cl_created_f7f204_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['ruc'], name='entities_pr_ruc_183116_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre'], name='entities_pr_nombre_e86a07_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['created_at'], name='entities_pr_created_a3db47_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['placa'], name='entities_un_placa_4fb12d_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['cliente'], name='entities_un_cliente_0e7688_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['tipo'], name='entities_un_tipo_305d18_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['marca', 'modelo'], name='entities_un_marca_b0db09_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['cliente', 'tipo'], name='entities_un_cliente_d30567_idx'),
        ),
    ]
